var calculator = {
subtraction:function(num1,num2){
return(num1-num2);
},
addition:function(num1,num2){
return(num1+num2);
},
multiple:function(num1,num2){
return(num1*num2);
},
division:function(num1,num2){
return(num1/num2);
},
exponents:function(num1,num2){
return(Math.pow(num1,num2));
},
square:function(num1,num2){
return(num1*num2);
}
}
